### ISSUE TITLE
[Suggestion] [QoL] Add "Auto All" On/Off switches for producers and producers upgrades purchase

### ISSUE THREAD

**Issue by Gormador** [FreakyFreakyNerd/FreakyFreakyNerd.github.io#1]
I often find myself disabling auto purchase for all producers / all prod upgrades one by one in order to push quarks and buy certain quark upgrades without waiting.  
A switch to toggle all of them (producers and producers upgrades separately, still) at once would be a massive time save.

I hope it's okay to provide you feedback through issues :-)

**Comment by FreakyFreakyNerd** [comment]
This has been added, and the changes should be up soon, thanks and good day
