### ISSUE TITLE
Synergy scores

### ISSUE THREAD

**Issue by kstone3** [FreakyFreakyNerd/FreakyFreakyNerd.github.io#2]
I'm fairly early game, around the 1e24 electrons range, recently unlocked orbitals and as I'm grinding through challenges I have seemed to notice that the synergy scores provide no benefit. I can always get a better score on a challenge without using the synergy scores than when I use them. Just wanted to let you know that this might need more tweaking. Also if their is a better place to talk like discord just let me know. Also I don't know how many players you have, but setting up a discord might be a good idea. I'm not great at it, but I could help if you want.

**Comment by FreakyFreakyNerd** [comment]
Yah currently the challenges are not greatly balanced, I am working on more balancing for them. The ultimate goal is to create a need for strategy to get the highest scores throughout the game. There is a discord if you would like to join https://discord.gg/DKRrQV2XU5
